# Generated by Django 4.2.5 on 2023-09-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=200)),
                ("Author_Name", models.CharField(max_length=300)),
                ("Content", models.CharField(max_length=1000)),
                ("URL", models.URLField()),
            ],
            options={"db_table": "Blog",},
        ),
    ]
